### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ishydin** [bagbek/salesforce-lwc-challenge#1]
Hi i need help deploying this to my salesforce org

**Comment by bagbek** [comment]
1) Clone the repository to your local machine using Git or download it as a ZIP file and extract its contents.

2) Ensure that you have Salesforce CLI (Command-Line Interface) installed on your machine. You can download and install it by following the instructions in the Salesforce CLI documentation: https://developer.salesforce.com/tools/sfdxcli

3) Open a command prompt or terminal and authenticate with your Salesforce org using Salesforce CLI. Run the following command and follow the authentication process prompted in your browser:

sfdx force:auth:web:login -d -a MyOrg

This command will authorize your CLI to connect with your Salesforce org, and the org will be named "MyOrg".

4) Use the cd command to navigate to the project directory that contains the Salesforce LWC challenge files.

5) Once you are in the project directory, deploy the LWC challenge to your Salesforce org using the following command:

sfdx force:source:deploy -p force-app

This command deploys the contents of the force-app directory, which contains the Salesforce metadata for the LWC challenge, to your org.

6) After the deployment process completes successfully, you can verify the deployment by checking your Salesforce org. The LWC components, Apex classes, and other metadata from the challenge should now be available in your org.

**Comment by ishydin** [comment]
can we have a quick call please if thats okay with you

**Comment by ishydin** [comment]
![image](https://user-images.githubusercontent.com/131690799/236706561-e88ed924-72b0-49e5-8041-06868b638728.png)![Capture11](https://user-images.githubusercontent.com/131690799/236706591-824c7d08-928f-459a-bb66-d1869ca7b2f6.PNG)

**Comment by ishydin** [comment]
![image](https://user-images.githubusercontent.com/131690799/236706785-e113dd59-290e-4b87-b21f-11ebd709b1da.png)

**Comment by ishydin** [comment]
please can you help

**Comment by ishydin** [comment]
nvm thank you
